// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modbus.Core.Persistence;

#nullable disable

namespace Modbus.Core.Persistence.Migrations
{
    [DbContext(typeof(ModbusDbContext))]
    [Migration("20260617160840_AddMqttCloudConfig")]
    partial class AddMqttCloudConfig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("Modbus.Core.Domain.Entities.DeviceModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte?>("DeviceCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<ushort?>("SqpfRegisterAddress")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("DeviceModels");
                });

            modelBuilder.Entity("Modbus.Core.Domain.Entities.ModbusDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DeviceModelId")
                        .HasColumnType("INTEGER");

                    b.Property<byte?>("FirmwareVersion")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<uint?>("SerialNumber")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("SlaveId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TransportType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceModelId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("Modbus.Core.Domain.Entities.RegisterDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("Address")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("DeviceModelId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWritable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("RegisterType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("ScaleFactor")
                        .HasColumnType("REAL");

                    b.Property<string>("Unit")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("WordOrder")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceModelId");

                    b.ToTable("RegisterDefinitions");
                });

            modelBuilder.Entity("Modbus.Core.Domain.Entities.RegisterValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("Address")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RawWords")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("RegisterType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "Address", "RegisterType")
                        .IsUnique();

                    b.ToTable("RegisterValues");
                });

            modelBuilder.Entity("Modbus.Core.Domain.Entities.ModbusDevice", b =>
                {
                    b.HasOne("Modbus.Core.Domain.Entities.DeviceModel", "DeviceModel")
                        .WithMany("Devices")
                        .HasForeignKey("DeviceModelId");

                    b.OwnsOne("Modbus.Core.Domain.ValueObjects.MqttConfig", "Mqtt", b1 =>
                        {
                            b1.Property<int>("ModbusDeviceId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("BrokerHost")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("TEXT")
                                .HasColumnName("MqttBrokerHost");

                            b1.Property<string>("ClientId")
                                .HasMaxLength(128)
                                .HasColumnType("TEXT")
                                .HasColumnName("MqttClientId");

                            b1.Property<string>("CommandTopic")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("TEXT")
                                .HasColumnName("MqttCommandTopic");

                            b1.Property<string>("Password")
                                .HasMaxLength(256)
                                .HasColumnType("TEXT")
                                .HasColumnName("MqttPassword");

                            b1.Property<int>("Port")
                                .HasColumnType("INTEGER")
                                .HasColumnName("MqttPort");

                            b1.Property<string>("ReplyTopic")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("TEXT")
                                .HasColumnName("MqttReplyTopic");

                            b1.Property<string>("TelemetryTopic")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("TEXT")
                                .HasColumnName("MqttTelemetryTopic");

                            b1.Property<bool>("UseTls")
                                .HasColumnType("INTEGER")
                                .HasColumnName("MqttUseTls");

                            b1.Property<string>("Username")
                                .HasMaxLength(128)
                                .HasColumnType("TEXT")
                                .HasColumnName("MqttUsername");

                            b1.HasKey("ModbusDeviceId");

                            b1.ToTable("Devices");

                            b1.WithOwner()
                                .HasForeignKey("ModbusDeviceId");
                        });

                    b.OwnsOne("Modbus.Core.Domain.ValueObjects.RtuConfig", "Rtu", b1 =>
                        {
                            b1.Property<int>("ModbusDeviceId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("BaudRate")
                                .HasColumnType("INTEGER")
                                .HasColumnName("RtuBaudRate");

                            b1.Property<int>("DataBits")
                                .HasColumnType("INTEGER")
                                .HasColumnName("RtuDataBits");

                            b1.Property<string>("Parity")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("RtuParity");

                            b1.Property<string>("PortName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("RtuPortName");

                            b1.Property<string>("StopBits")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("RtuStopBits");

                            b1.HasKey("ModbusDeviceId");

                            b1.ToTable("Devices");

                            b1.WithOwner()
                                .HasForeignKey("ModbusDeviceId");
                        });

                    b.OwnsOne("Modbus.Core.Domain.ValueObjects.TcpConfig", "Tcp", b1 =>
                        {
                            b1.Property<int>("ModbusDeviceId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("IpAddress")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("TcpIpAddress");

                            b1.Property<int>("Port")
                                .HasColumnType("INTEGER")
                                .HasColumnName("TcpPort");

                            b1.HasKey("ModbusDeviceId");

                            b1.ToTable("Devices");

                            b1.WithOwner()
                                .HasForeignKey("ModbusDeviceId");
                        });

                    b.Navigation("DeviceModel");

                    b.Navigation("Mqtt");

                    b.Navigation("Rtu");

                    b.Navigation("Tcp");
                });

            modelBuilder.Entity("Modbus.Core.Domain.Entities.RegisterDefinition", b =>
                {
                    b.HasOne("Modbus.Core.Domain.Entities.DeviceModel", "DeviceModel")
                        .WithMany("Registers")
                        .HasForeignKey("DeviceModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeviceModel");
                });

            modelBuilder.Entity("Modbus.Core.Domain.Entities.RegisterValue", b =>
                {
                    b.HasOne("Modbus.Core.Domain.Entities.ModbusDevice", "Device")
                        .WithMany("RegisterValues")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Modbus.Core.Domain.Entities.DeviceModel", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("Registers");
                });

            modelBuilder.Entity("Modbus.Core.Domain.Entities.ModbusDevice", b =>
                {
                    b.Navigation("RegisterValues");
                });
#pragma warning restore 612, 618
        }
    }
}
