namespace Modbus.Desktop.Services.Strings;

internal static class PortugueseStrings
{
    public static readonly Dictionary<string, string> All = new()
    {
        // Navigation
        ["NavDevices"]           = "Dispositivos",
        ["NavSettings"]          = "Configurações",

        // MainWindow sidebar
        ["AppSubtitle"]          = "Monitor de Dispositivos",

        // DeviceListView
        ["Devices"]              = "Dispositivos",
        ["AddDevice"]            = "+ Adicionar Dispositivo",
        ["Refresh"]              = "Atualizar",
        ["NoDevicesFound"]       = "Nenhum dispositivo encontrado. Adicione um dispositivo para começar.",
        ["Open"]                 = "Abrir →",
        ["Delete"]               = "Excluir",
        ["NeverSeen"]            = "Nunca visto",
        ["UnknownModel"]         = "Modelo desconhecido",
        ["AddrPrefix"]           = "End. {0}",

        // Delete dialog
        ["ConfirmDelete"]        = "Confirmar Exclusão",
        ["ConfirmDeleteMsg"]     = "Excluir \"{0}\"? Esta ação não pode ser desfeita.",
        ["Cancel"]               = "Cancelar",

        // Mass-memory reset confirmation (IoT grandezas / send interval change)
        ["CfgMemResetTitle"]     = "Reiniciar memória de massa",
        ["CfgMemResetMsg"]       = "Alterar as grandezas e/ou o intervalo de envio reinicia a memória de massa do medidor, apagando os dados já registrados. Deseja continuar?",
        ["CfgMemResetConfirm"]   = "Continuar",

        // AddDeviceView
        ["Back"]                 = "← Voltar",
        ["AddDeviceTitle"]       = "Adicionar Dispositivo",
        ["TransportType"]        = "Tipo de Transporte",
        ["RtuOption"]            = "RTU (Porta Serial)",
        ["TcpOption"]            = "TCP (Ethernet / Wi-Fi)",
        ["CloudOption"]          = "Nuvem (broker MQTT)",
        ["CloudSettings"]        = "Configurações do Broker em Nuvem",
        ["CloudSettingsHint"]    = "Lê medidores de campo por um broker MQTT em nuvem. O medidor publica telemetria JSON e aceita comandos no tópico de reply.",
        ["BrokerHost"]           = "Host do Broker",
        ["BrokerHostWatermark"]  = "ex.: mqtt.kron.com.br",
        ["BrokerPort"]           = "Porta",
        ["BrokerUseTls"]         = "Usar TLS",
        ["BrokerUsername"]       = "Usuário",
        ["BrokerPassword"]       = "Senha",
        ["CloudSerial"]          = "Número de Série",
        ["CloudSerialWatermark"] = "série do medidor (identifica o tópico)",
        ["DeviceModel"]          = "Modelo do Dispositivo",
        ["CloudSerialRequired"]  = "Número de série e host do broker são obrigatórios para dispositivos de nuvem.",
        ["TelemetryTopic"]       = "Tópico de Dados",
        ["TelemetryTopicHint"]   = "Tópico onde o medidor publica telemetria/respostas (específico da instalação, ex.: \"ks\").",
        // Telas de leitura / configuração de nuvem
        ["CloudReadingsTitle"]   = "Telemetria",
        ["CloudReadingsWaiting"] = "Aguardando telemetria do medidor… Só aparecem as grandezas que o medidor publicar no broker.",
        ["CloudConfigTitle"]     = "Configuração MQTT",
        ["CfgMeasurement"]       = "Medição",
        ["CfgCloud"]             = "Nuvem (telemetria)",
        ["CfgRelay"]             = "Saída Digital (relé)",
        ["CfgActions"]           = "Ações",
        ["CfgTP"]                = "Relação TP",
        ["CfgTC"]                = "Relação TC",
        ["CfgTL"]                = "Tipo de ligação (0/1/2/48/49)",
        ["CfgTI"]                = "Integração de demanda (min)",
        ["CfgKE"]                = "Constante de pulso (LED)",
        ["CfgTHRS"]              = "Threshold do horímetro (A)",
        ["CfgRT"]                = "Blocos de retransmissão MQTT",
        ["CfgIA"]                = "Intervalo de envio (min)",
        ["CfgRelayOn"]           = "Relé ligado (SD1)",
        ["CfgApply"]             = "Aplicar",
        ["CfgApplyGrandezas"]    = "Aplicar grandezas",
        ["CfgGrandezas"]         = "Grandezas da nuvem (G1..G20)",
        ["CfgGrandezasHint"]     = "Números dos Input Registers (30003..39999). Use 65535 para encerrar a lista.",
        ["CfgResetNote"]         = "Atenção: alterar TL, IA ou grandezas reinicia o medidor.",
        ["CfgResetDevice"]       = "Reiniciar dispositivo",
        ["CfgResetEnergies"]     = "Zerar energias/demandas",
        ["CfgInitHourmeter"]     = "Inicializar horímetro",
        ["CfgResetMqttBuffer"]   = "Resetar buffer MQTT",
        ["CloudConfigSent"]      = "Comando enviado.",
        ["CloudConfigNothingToSend"] = "Nada a enviar — preencha ao menos um campo.",
        ["SerialPortSettings"]   = "Configurações da Porta Serial",
        ["ComPort"]              = "Porta COM",
        ["RefreshPortList"]      = "Atualizar lista de portas",
        ["BaudRate"]             = "Baud Rate",
        ["DataBits"]             = "Data Bits",
        ["Parity"]               = "Parity",
        ["StopBits"]             = "Stop Bits",
        ["AddressRange"]         = "Faixa de Endereços",
        ["NetworkSettings"]      = "Configurações de Rede",
        ["NetworkSettingsHint"]  = "A descoberta usa broadcast UDP (255.255.255.255). Os dispositivos na rede local responderão automaticamente.",
        ["SearchNetwork"]        = "Buscar na Rede",
        ["FoundDevices"]         = "Dispositivos Encontrados",
        ["NoFoundDevicesYet"]    = "Nenhum dispositivo encontrado. Execute uma varredura ou preencha os detalhes manualmente abaixo.",
        ["DeviceDetails"]        = "Detalhes do Dispositivo",
        ["Name"]                 = "Nome",
        ["DeviceNameWatermark"]  = "ex.: KS-3000 #0012345",
        ["Address"]              = "Endereço (1–247)",
        ["DeviceIp"]             = "IP do Dispositivo",
        ["DeviceIpWatermark"]    = "ex.: 192.168.1.42",
        ["SaveDevice"]           = "Salvar Dispositivo",

        // AddDeviceViewModel status messages
        ["Ready"]                = "Pronto",
        ["SelectComPortFirst"]   = "Selecione uma porta COM primeiro.",
        ["ScanningProgress"]     = "Varrendo {0} ({1}/{2})",
        ["ScanDone"]             = "Concluído — {0} dispositivo(s) encontrado(s).",
        ["ScanNoResponse"]       = "Varredura concluída. Nenhum dispositivo respondeu.",
        ["ScanCancelled"]        = "Varredura cancelada.",
        ["ErrorPrefix"]          = "Erro: {0}",
        ["DuplicateSerial"]      = "Já existe um dispositivo com o número de série {0:D7}.",
        ["DuplicateIp"]          = "Já existe um dispositivo com o IP {0}.",
        ["DuplicateRtuAddress"]  = "Já existe um dispositivo no endereço RTU {0}.",
        ["ConnectFailed"]        = "Não foi possível conectar ao dispositivo. Verifique o endereço e as configurações.",
        ["CheckingAddress"]      = "Verificando disponibilidade do endereço...",
        ["WritingAddress"]       = "Gravando novo endereço no medidor...",
        ["WaitingForReboot"]     = "Aguardando reinicialização do medidor (~20 s)...",
        ["AddressOccupied"]      = "Endereço {0} já está em uso na rede.",
        ["AddressChangeTimeout"] = "O medidor não respondeu no endereço {0}. Verifique e tente novamente.",
        ["DeviceSaved"]          = "Dispositivo salvo. Selecione outro da lista ou volte.",

        // DeviceDetailView
        ["Transport"]            = "Transporte",
        ["Connection"]           = "Conexão",
        ["SlaveAddress"]         = "Endereço",
        ["Model"]                = "Modelo",
        ["Unknown"]              = "Desconhecido",

        // Electrical Readings — Tabs
        ["TabInstantaneous"]     = "Leituras instantâneas",
        ["TabEnergiesDemands"]   = "Energias / Demandas",
        ["TabInputsOutputs"]     = "Entradas e Saídas",
        ["TabHourmeter"]         = "Horímetro",
        ["TabStatus"]            = "Status",
        ["TabComingSoon"]        = "Em breve",
        ["NoLiveData"]           = "Sem dados ao vivo. Aguardando próxima leitura...",

        // Electrical Readings — Groups
        ["GroupVoltages"]        = "Tensões",
        ["GroupCurrents"]        = "Correntes",
        ["GroupFrequency"]       = "Frequência",
        ["GroupActivePower"]     = "Potência Ativa",
        ["GroupReactivePower"]   = "Potência Reativa",
        ["GroupApparentPower"]   = "Potência Aparente",
        ["GroupPowerFactor"]     = "Fator de Potência",
        ["GroupEnergies"]        = "Energias",
        ["GroupDemands"]         = "Demandas",
        ["GroupOther"]           = "Outros",

        // Hourmeter Tab
        ["HmTitle"]              = "Carga 1",
        ["HmHourmeter"]          = "Horímetro",

        // IO Tab
        ["IoSectionInputs"]      = "Entradas Digitais",
        ["IoSectionOutputs"]     = "Saídas Digitais",
        ["IoStatus"]             = "Estado:",
        ["IoCounter"]            = "Contador:",
        ["IoPulseWidth"]         = "Largura do Pulso:",
        ["IoReset"]              = "Zerar",
        ["IoTurnOn"]             = "Ligar",
        ["IoTurnOff"]            = "Desligar",
        ["IoStateOn"]            = "LIGADA",
        ["IoStateOff"]           = "DESLIGADA",

        // Electrical Readings — Register descriptions
        ["RegU0"]                = "Trifásica",
        ["RegU12"]               = "Fase A-B",
        ["RegU23"]               = "Fase B-C",
        ["RegU31"]               = "Fase C-A",
        ["RegU1"]                = "Linha 1",
        ["RegU2"]                = "Linha 2",
        ["RegU3"]                = "Linha 3",
        ["RegI0"]                = "Trifásica",
        ["RegI1"]                = "Linha 1",
        ["RegI2"]                = "Linha 2",
        ["RegI3"]                = "Linha 3",
        ["RegFreq"]              = "Linha 1",
        ["RegP0"]                = "Trifásica",
        ["RegP1"]                = "Linha 1",
        ["RegP2"]                = "Linha 2",
        ["RegP3"]                = "Linha 3",
        ["RegQ0"]                = "Trifásica",
        ["RegQ1"]                = "Linha 1",
        ["RegQ2"]                = "Linha 2",
        ["RegQ3"]                = "Linha 3",
        ["RegS0"]                = "Trifásica",
        ["RegS1"]                = "Linha 1",
        ["RegS2"]                = "Linha 2",
        ["RegS3"]                = "Linha 3",
        ["RegFP0"]               = "Trifásico",
        ["RegFP1"]               = "Linha 1",
        ["RegFP2"]               = "Linha 2",
        ["RegFP3"]               = "Linha 3",

        // DeviceHubView
        ["HubReadings"]              = "Leituras",
        ["HubReadingsDesc"]          = "Tensões, correntes, potências e frequência lidos diretamente do medidor.",
        ["HubMassMemory"]            = "Memória de Massa",
        ["HubMassMemoryDesc"]        = "Histórico de medições armazenado internamente no medidor.",
        ["HubConfigure"]             = "Configurar",
        ["HubConfigureDesc"]         = "Altere parâmetros e configurações do medidor via escrita de registradores.",

        // Status Tab
        ["StsMeterTitle"]        = "Status Medidor",
        ["StsModuleTitle"]       = "Status Módulo",
        ["StsCodeHeader"]        = "Código - Descrição",
        ["StsNoErrors"]          = "Sem erros ativos.",

        // DeviceItemViewModel
        ["Connected"]            = "Conectado",
        ["Disconnected"]         = "Desconectado",

        // RegisterValueViewModel
        ["RegisterFallback"]     = "Registrador {0}",

        // DeviceConfigureView — navegação lateral
        ["ConfigureTitle"]       = "Configurar",
        ["CfgGeneral"]           = "Configurações Gerais",
        ["CfgEthernet"]          = "Ethernet",
        ["CfgWireless"]          = "Sem fio",
        ["CfgSntp"]              = "SNTP",
        ["CfgIot"]               = "IoT",
        ["CfgClock"]             = "Relógio",
        ["CfgInputsOutputs"]     = "Entradas e Saídas",

        // DeviceConfigureView — faixa de informações do dispositivo
        ["CfgSerial"]            = "Série",
        ["CfgFirmware"]          = "Firmware",
        ["CfgHardware"]          = "Hardware",

        // DeviceConfigureView — campos comuns
        ["CfgEnabled"]           = "Habilitado",
        ["CfgDisabled"]          = "Desabilitado",
        ["CfgManual"]            = "Manual",
        ["CfgUseNow"]            = "Usar agora",
        ["CfgEditButton"]        = "Alterar",
        ["CfgSaveButton"]        = "Salvar",
        ["CfgCancelButton"]      = "Cancelar",
        ["CfgRetryRead"]         = "Tentar novamente",
        ["CfgSaveSuccess"]       = "Configurações gravadas",
        ["CfgSaveError"]         = "Erro ao gravar configurações",
        ["CfgSavePartialReboot"] = "Aplicado {0} de {1}. Dispositivo reiniciando, retomando…",
        ["CfgSaveDeviceDownAfterPartial"] = "Aplicado {0} de {1}. Dispositivo não voltou a tempo. Aguarde alguns instantes e tente novamente os campos faltantes.",
        ["CfgSaveStillIncomplete"] = "Aplicado {0} de {1} após {2} reinicializações. Alguns campos não foram gravados.",
        ["CfgSaveSuccessReadIncomplete"] = "Configurações gravadas — não foi possível reler todos os campos para confirmar.",
        ["CfgSaveSuccessDeviceRebooting"] = "Configurações gravadas — o dispositivo está reiniciando. Clique em 'Tentar novamente' assim que voltar online para reler.",
        ["CfgSecurityNone"]      = "Nenhuma",
        ["CfgBrokerDefault"]     = "Padrão",

        // DeviceConfigureView — Configurações Gerais
        ["CfgCode"]              = "Código",
        ["CfgDeviceDesc"]        = "Descrição",
        ["CfgConnectionType"]    = "Tipo de Ligação (TL)",
        ["CfgIntegrationTime"]   = "Integração (TI)  0 – 60",
        ["CfgCurrentInvert"]     = "Inverter corrente",
        ["CfgPfSequence"]        = "Sequência do Ponto Flutuante (Seq. PF)",
        ["CfgThreshold"]         = "Threshold  (0,01 – 9999,99)",
        ["CfgConfigPassword"]    = "Senha de configuração",

        // DeviceConfigureView — Ethernet
        ["CfgDhcp"]              = "DHCP automático",
        ["CfgIpAddress"]         = "Endereço IP",
        ["CfgSubnetMask"]        = "Máscara de sub-rede",
        ["CfgGateway"]           = "Gateway padrão",
        ["CfgDns"]               = "DNS",
        ["CfgMacAddress"]       = "Endereço MAC",

        // DeviceConfigureView — Sem fio
        ["CfgMode"]              = "Modo",
        ["CfgSecurity"]          = "Segurança",
        ["CfgWifiPassword"]      = "Senha Wi-Fi",
        ["CfgModuleVersion"]     = "Ver. módulo",
        ["CfgBtPassword"]        = "Senha",

        // DeviceConfigureView — SNTP
        ["CfgNtpServer"]         = "Servidor SNTP",
        ["CfgTimezone"]          = "Fuso horário",
        ["CfgSyncInterval"]      = "Int. de sincronismo",
        ["CfgUnitHours"]         = "hora(s)",
        ["CfgUnitMinutes"]       = "minuto(s)",

        // DeviceConfigureView — IoT / MQTT
        ["CfgSendInterval"]      = "Intervalo de envio",
        ["CfgSendOnHour"]        = "Envio em hora cheia",
        ["CfgMqttBroker"]        = "Broker",
        ["CfgMqttDescId"]        = "Descrição / ID",
        ["CfgMqttPort"]          = "Porta",
        ["CfgMqttTopic"]         = "Tópico",
        ["CfgMqttUser"]          = "Nome de usuário",
        ["CfgMqttToken"]         = "Token / Senha",
        ["CfgKeepAlive"]         = "Manter conexão ativa",
        ["CfgKronCloud"]         = "KronCloud",
        ["CfgTls"]               = "TLS",
        ["CfgClearBuffer"]       = "Apagar Buffer",
        ["CfgAvailableRegisters"]= "Grandezas disponíveis",
        ["CfgSelectedRegisters"] = "Selecionadas",
        ["CfgIotTabCerts"]       = "Certificados",
        ["CfgIotTabRetransmit"]  = "Retransmitir blocos",
        ["CfgGrandezaCounter"]     = "Selecionadas ({0}/{1})",
        ["CfgGrandezaAdd"]         = "Adicionar selecionadas",
        ["CfgGrandezaRemove"]      = "Remover selecionadas",
        ["CfgGrandezaClear"]       = "Remover todas",
        ["CfgGrandezaLimitReached"]= "Limite de {0} grandezas atingido.",

        // DeviceConfigureView — Relógio
        ["CfgDate"]              = "Data",
        ["CfgTime"]              = "Hora",

        // DeviceConfigureView — Entradas e Saídas
        ["CfgDebounceEdp"]       = "Debounce EDPs",

        // MassMemoryView
        ["MmSerial"]             = "Série",
        ["MmAddress"]            = "Endereço",
        ["MmDescription"]        = "Descrição",
        ["MmInterval"]           = "IA",
        ["MmMode"]               = "MA",
        ["MmMinutes"]            = "Minutos",
        ["MmModeCircular"]       = "Circular",
        ["MmModeLinear"]         = "Linear",
        ["MmStartReading"]       = "Iniciar Leitura",
        ["MmPauseReading"]       = "Pausar Leitura",
        ["MmExportTxt"]          = "Exportar TXT",
        ["MmNoGrandezas"]        = "Nenhuma grandeza configurada para memória de massa.",
        ["MmReading"]            = "Lendo bloco {0} de {1}...",
        ["MmReadComplete"]       = "Concluído — {0} blocos lidos.",
        ["MmReadCancelled"]      = "Interrompido — {0} blocos lidos.",
        ["MmReadError"]          = "Erro na leitura: {0}",
        ["MmEmpty"]              = "Memória sem registros gravados.",
        ["MmControlBlockFailed"]  = "Falha ao ler o bloco de controle. Verifique a conexão e tente novamente.",
        ["MmResumeTitle"]         = "Retomar leitura",
        ["MmResumeMsg"]           = "Deseja continuar de onde parou ou começar do zero?",
        ["MmResumeContinue"]      = "Continuar",
        ["MmResumeRestart"]       = "Começar do zero",

        // SettingsView
        ["SettingsTitle"]        = "Configurações",
        ["Language"]             = "Idioma",
        ["ChangeInSettings"]     = "Alterar nas Configurações",
        ["NoPortConfigured"]     = "Nenhuma porta COM configurada.",
        ["PortUnavailable"]      = "Porta não conectada. Verifique se o dispositivo está plugado.",
    };
}
